signBytes = b"$\xCC\xC8$"

replacements = [
    (b"idata", b".1_"),
    (b"\xFF\xFF\xFF", b".2_"),
    (b"\x00\x00\x00\x00\x00", b".3_"),
    (b"ZZZZZZ", b".4_"),
    (b"This program cannot be run in DOS mode.", b".5_"),
    (b"\x70\x6F\x8D", b".6_"),
    (b"__Display", b".7_"),
    (b"<update>", b".8_"),
    (b"\xC1\xC1\xC1\xFF\xC1\xC1\xC1\xFF", b".9_"),
    (b"\xC4\xC4\xC4\xFF\xC4\xC4\xC4\xFF", b".0_"),
    (b"\xC0\xC0\xC0\xFF\xC0\xC0\xC0\xFF", b".$^"),
    (b"\xCC\xCC\xCC\xCC\xCC\xCC", b".!d^"),
    (b"System", b".@_"),
    (b"kwsc", b".{_"),
    (b"$char_traits", b".c!t_"),
    (b"tttttt", b".\xC0_"),
    (b"cccccc", b".\xC1_"),
    (b"gggggg", b".\xC2_"),
    (b"\x90\x90\x90\x90\x90\x90", b".\xC3_"),
    (b"\x80\x80\x80\x80\x80\x80", b".\xC4_"),
    (b"\xf6\xc4\x01t\x05", b".\xC5_"),
    (b"\xff\xf5\xf5\xf5\xff\xf5", b".\xC6_"),
    (b"\xf5\xff\xf5\xf5\xf5\xff", b".\xC7_"),
    (b"\xcc\xcc\xcc\xcc\xcc\xcc", b".\xC8_"),
    (b"KERNEL32.dll", b".d1_"),
    (b"USER32.dll", b".d2_"),
    (b"ADVAPI32.dll", b".d3_"),
    (b"MSVCRT.dll", b".d4_"),
    (b"GetProcAddress", b".d5_"),
    (b"LoadLibraryA", b".d6_"),
    (b"GetModuleHandle", b".d7_"),
    (b"VirtualAlloc", b".d8_"),
    (b"Sleep", b".d9_"),
    (b"\x55\x8B\xEC", b".e1_"),
    (b"\x8B\x45\x08", b".e2_"),
    (b"\x33\xC0\x5D\xC3", b".e3_"),
    (b"\x83\xEC\x08", b".e4_"),
    (b"\xE8\x00\x00\x00\x00", b".e5_"),
    (b"\x00\x00\x00\x00\x00\x00\x00\x00", b".e6_"),
    (b".rdata", b".f1_"),
    (b".reloc", b".f2_"),
    (b".text", b".f3_"),
    (b".data", b".f4_"),
    (b"Padding", b".f5_"),
    (b"Microsoft", b".f6_"),
    (b"Copyright", b".f7_"),
    (b"https://", b".g1_"),
    (b"http://", b".g2_"),
    (b"Content-Type:", b".g3_"),
    (b"application/", b".g4_"),
    (b"utf-8", b".g5_"),
    (b"index.html", b".g6_"),
    (b"Connection: keep-alive", b".g7_"),
    (b"\x20\x20\x20\x20\x20\x20\x20\x20", b".h1_"),
    (b"\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF", b".h2_"),
    (b"AAAAAAAA", b".h3_"),
]